### ISSUE TITLE
albums抓取不到订阅过的作者，motions正常

### ISSUE THREAD

**Issue by hanzhsun** [PhiFever/AfdianToMarkdown#10]
motions抓取成功，albums显示“登陆已过期”，免费内容也抓取不到
![image](https://github.com/user-attachments/assets/1d4dcafd-2093-49a5-a59b-fddc63a5c065)
推测是因为之前订阅过这个作者
用9adgq（从未订阅）测试了一下，albums抓取成功
![image](https://github.com/user-attachments/assets/0863ef20-2f46-44af-9e38-a6e6ed4c896c)

**Comment by jjtnb123** [comment]
你好哥们

**Comment by jjtnb123** [comment]
你是怎么操作的

**Comment by jjtnb123** [comment]
![cc531044-1489-4f99-842a-8ab74ce1d926](https://github.com/user-attachments/assets/7aae5781-a6b8-4bd8-ba36-151132146e05)
你有没有遇到这个问题，我明明把cookies文件放进和exe同一目录下了

**Comment by jjtnb123** [comment]
![Uploading b148fa2a-2d63-4b94-861e-8d03037772fb.png…]()

**Comment by jjtnb123** [comment]
![b148fa2a-2d63-4b94-861e-8d03037772fb](https://github.com/user-attachments/assets/a3ab1181-0f7f-4198-8cfe-fe710c29054a)

**Comment by hanzhsun** [comment]
1.  `cd /d E:\zhuomian\...` 你的文件夹 或者 直接如图打开terminal
![image](https://github.com/user-attachments/assets/94013988-2579-4fe2-a4b2-5245ad4501da)
2. `./AfdianToMarkdown.exe --host='afdian.com' -au omomomomomomo motions`

**Comment by jjtnb123** [comment]
谢谢，你的回答很有帮助

**Comment by PhiFever** [comment]
> motions抓取成功，albums显示“登陆已过期”，免费内容也抓取不到 ![image](https://private-user-images.githubusercontent.com/48179160/357266826-1d4dcafd-2093-49a5-a59b-fddc63a5c065.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjQ1MTAsIm5iZiI6MTcyMzUyNDIxMCwicGF0aCI6Ii80ODE3OTE2MC8zNTcyNjY4MjYtMWQ0ZGNhZmQtMjA5My00OWE1LWE1OWItZmRkYzYzYTVjMDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MzVmYzI4N2U5ZGI2MjVjNzQ0OTZlMDQ3YmE0ZDRmYjMxYTVkMDEzZGU5N2JmNzViYzgxMTg2ZTAzNWUwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gv6OQPZ4J73RXanAu4Z7hvgS0CmYO6V7Sz1j-D_2rNE) 推测是因为之前订阅过这个作者 用9adgq（从未订阅）测试了一下，albums抓取成功 ![image](https://private-user-images.githubusercontent.com/48179160/357268097-0863ef20-2f46-44af-9e38-a6e6ed4c896c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjQ1MTAsIm5iZiI6MTcyMzUyNDIxMCwicGF0aCI6Ii80ODE3OTE2MC8zNTcyNjgwOTctMDg2M2VmMjAtMmY0Ni00NGFmLTllMzgtYTZlNmVkNGM4OTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNzZiZmYyN2FkOTY0MjdhMWU4NTM5NTZhNjQ3MTI3Njc1ZWYzZGUyZDFhZWQxNGJjOTFiMzUzMjc3N2MyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VqsorThte7-TOBuGPEIjBO543aFBrXRVU7BqlfW7A78)

试试在浏览器上清除掉所有的cookie之后重新登录，再重新向程序中导入一遍cookie？

**Comment by hanzhsun** [comment]
重新导入不能解决这个问题，但我参考[之前的pull request](https://github.com/PhiFever/AfdianToMarkdown/pull/4)，在header里应用直接从浏览器黏贴的完整的cookies后albums抓取成功

**Comment by PhiFever** [comment]
从header中导出的authToken字段和使用插件导出的结果不一样吗？

**Comment by hanzhsun** [comment]
> 从header中导出的authToken字段和使用插件导出的结果不一样吗？

1. get-album-info必须用完整的cookie，包括_ga=...
只传auth_token就会得到“登录已过期”的结果（其他只用auth_token是ok的
2. 导出的auth_token是一样的
我浏览器开了屏蔽插件，所以之前导出的cookie只有auth_token, 不包含其他的……

**Comment by PhiFever** [comment]
第二点确实没想到，您提出的设想也很有道理……唯一的问题是，我目前使用的cookie在只有一个auth_token的情况下仍然能成功使用album功能。。。删除浏览器上的cookie后登录重新导出仍然如此。
![image](https://github.com/user-attachments/assets/8c4ff79c-ca9a-42cd-80f6-bcd40051bb7b)

**Comment by hanzhsun** [comment]
> 第二点确实没想到，您提出的设想也很有道理……唯一的问题是，我目前使用的cookie在只有一个auth_token的情况下仍然能成功使用album功能。。。删除浏览器上的cookie后登录重新导出仍然如此。 ![image](https://private-user-images.githubusercontent.com/83220033/358278642-8c4ff79c-ca9a-42cd-80f6-bcd40051bb7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NTgwNzUsIm5iZiI6MTcyMzc1Nzc3NSwicGF0aCI6Ii84MzIyMDAzMy8zNTgyNzg2NDItOGM0ZmY3OWMtY2E5YS00MmNkLTgwZjYtYmNkNDAwNTFiYjdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDIxMzYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMDc3NDExMjEzN2QzZmYzYjkxY2NlMjYxN2Q5ZGI2ZjA5ZGIyODFkMTE0OTI5ZjYzYzE5ZWFkNDJlMWFhOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0osLEhnVNj5cybiDsRv24JwmzipEa6UXAw11qc4CIgQ)

可能是因为你**没有订阅过**这个作者，我之前也提到了这种情况。
这是我测试过的：
1. 从未订阅过 - 仅auth_token，motions抓取成功，albums成功
2. 曾经订阅过 - 仅auth_token，motions抓取成功，**albums失败**
a. 目前在订阅
b. 目前未订阅

**Comment by PhiFever** [comment]
我明白您的意思，我有为这位作者发电3个月的“礼”徽章。

**Comment by hanzhsun** [comment]
是连续发电到现在吗？中间有断过吗？我没有这样的例子来测试。我试的几个都是中间有段时间没发电，所以猜测是不是这个因素有影响？

**Comment by PhiFever** [comment]
我在今年的3月，6、7、8月都发过电。爱发电7月换过域名，如果按换之后过来看确实是连续发电。

**Comment by hanzhsun** [comment]
应该是换域名的影响，我以前的发电记录都在七月之前。

**Comment by PhiFever** [comment]
fixed [bug fix: can not get posts from albums](https://github.com/PhiFever/AfdianToMarkdown/pull/12)
