### ISSUE TITLE
打开程序时闪退

### ISSUE THREAD

**Issue by lionhearttt** [PhiFever/AfdianToMarkdown#3]
打扰uu，不知道是不是我打开方式不对，打开就闪退了，以及main go改Flags: []cli.Flag{ 对应的三个参数就可以呢
![微信图片_20240806164108](https://github.com/user-attachments/assets/c43c5a09-bf61-451c-a0a1-821889c0c5d4)
我可能太蠢了hhh
uu如果方便可不可以举个具体点例子、、谢谢！

**Comment by PhiFever** [comment]
本程序为命令行程序，需要在命令行中传入参数进行调用。请参考最新的README或#2中的示例。
