### ISSUE TITLE
您好，请问出现 open cookies.json: The system cannot find the file specified.是为什么？明明已经创建了cookies.json文件

### ISSUE THREAD

**Issue by Dstmr** [PhiFever/AfdianToMarkdown#6]
如图

![屏幕截图 2024-08-09 095629](https://github.com/user-attachments/assets/abbc3611-7333-4fd8-bf15-bd01b464727b)
rutu
![屏幕截图 2024-08-09 095654](https://github.com/user-attachments/assets/c8343fc6-e857-487a-95e0-fcf32e982d35)

**Comment by Dstmr** [comment]
已解决，在PowerShell上会出现上述问题，但在cmd上可以正常使用

**Comment by PhiFever** [comment]
这是由于程序的路径问题导致的，您目前是在`C:\Users\Administrator`下工作并在该目录下调用了`D:\AIFADAIN\AfdianToMarkdown.exe` 。而本程序会自动寻找当前工作目录下的`cookies.json`，因此它显然无法找到您目标文件夹下的文件。要修复您提出的问题，请尝试通过`cd D:\AIFADAIN\AfdianToMarkdown.exe`命令来移动工作目录到程序目录下再使用。
