### ISSUE TITLE
我遇到一些问题

### ISSUE THREAD

**Issue by jjtnb123** [PhiFever/AfdianToMarkdown#7]
你好xd，我是一个零基础小白，我用了你给的教程遇到了一点问题，我不知道我哪一步
做错了，他提示我cookies.json找不到。![b6dd1c83-5642-4b2a-8169-581da200f82f](https://github.com/user-attachments/assets/4bad110d-35e8-494b-adc3-93542d979511)
![abf31d3d-8b77-42b9-8a8d-ff3bb368e43a](https://github.com/user-attachments/assets/ce24c618-89fe-4cda-bcdc-2b65754d163b)

**Comment by PhiFever** [comment]
请参阅#6，解决方法相同。在cmd下的命令语法与powershell略有不同，需要先`D:`再`cd xxx/your/path`
