### ISSUE TITLE
提问前必看

### ISSUE THREAD

**Issue by PhiFever** [PhiFever/AfdianToMarkdown#8]
## 如何使您的问题更容易得到快速的解决
请参考[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

具体来说，您可以在提出的issue中附上尽量多的运行截图（请注意不要泄漏个人信息）或者可复现的操作流程。作者不会占卜，否则我可以帮您起一卦算算程序为什么不能运行（）

## 常见的问题解答

在提出问题前，请确保您已经完整的阅读了README和issue

1. Q：抓取到的文章正文为空/只能抓取到免费文章

   A：请使用浏览器插件`cookie master`导出cookie，且爱发电账号需要有订阅

2. Q：双击程序后闪退

   A：本程序为命令行程序，需要在命令行中传入参数进行调用。请参考README

3. Q：创建并导入`cookies.json`后仍然报错open cookies.json: The system cannot find the file specified

   A：通过`cd`命令移动工作目录到程序目录下再重新执行，程序只会寻找当前工作目录下的`cookies.json`

**Comment by jjtnb123** [comment]
所以你就删除了我的提问吗

**Comment by jjtnb123** [comment]
我知道了，给你添麻烦了

**Comment by jjtnb123** [comment]
意思是说我至少订阅他的一个项目，就可以爬取他的所有吗

**Comment by PhiFever** [comment]
> 所以你就删除了我的提问吗

我只是关闭了您的issue，因为它是一个已解决的问题。通常来说，issue在open状态下表示它是一个仍然需要讨论的问题，需要其他社区成员提供帮助或提出者给出更多信息。

所以并不是我认为您的问题太傻了之类的所以删了它(๑ᵔ⌔ᵔ๑)，只是认为它不再需要额外的讨论，您仍然可以在issue列表里找到它以便于后来的朋友们参考。

**Comment by PhiFever** [comment]
> 意思是说我至少订阅他的一个项目，就可以爬取他的所有吗

理论上来说本程序可以爬取爱发电上某个指定作者的所有公开和已订阅的纯文本内容。

**Comment by jjtnb123** [comment]
谢谢

**Comment by jjtnb123** [comment]
我照你说的做了但是仍然仍然报错open cookies.json: The system cannot find the file specified

**Comment by jjtnb123** [comment]
它和exe在同一个目录内
